### PR TITLE
enable dark mode theme

### PR DESCRIPTION
**Pull request by OleksandrHrybovoda**

### CODE REVIEW

**Comment by stuartkuentzel** [comment]
this looks great. is it possible to change the colors of the tables as well?

**Comment by OleksandrHrybovoda** [comment]
yes, what colors do you prefer?

**Comment by stuartkuentzel** [comment]
@OleksandrHrybovoda i think the same dark grey used in the header for the background of the tables.

**Comment by stuartkuentzel** [comment]
closes #1

**Pull request merged**
